name: Fetch headlines

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour at minute 0

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test e2e/

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: playwright-report/
          retention-days: 7
