name: Fetch headlines

on:
  push:
  schedule:
    - cron: "0 * * * *" # Runs every hour at minute 0

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test e2e/

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/rnz.txt data/nzh.txt data/thepost.txt data/bd.txt data/1news.txt
          git commit -am "Update headlines" -a || echo "No changes to commit"
          git push
