name: Fetch headlines

on:
  push:
  schedule:
    - cron: "0 * * * *" # Runs every hour at minute 0

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: npx playwright test e2e/rnz.spec.ts e2e/post.spec.ts --project firefox

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: data
          path: |
            data/

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/rnz.txt data/thepost.txt
          git commit -am "Update headlines" -a || echo "No changes to commit"
          git push
